repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format (auto-format & add)
        entry: scripts/hooks/clang-format-and-add.sh
        language: script
        files: '\\.(c|cpp|cc|h|hpp)$'
